[tool.poetry.dependencies]
python = "^3.11"
nextcord = ">=2.5"
aiomysql = ">=0.2"
cryptography = ">=41.0.0"
glicko2 = ">=2.0"
trueskill = ">=0.4.5"
emoji = ">=2.7"
prettytable = ">=3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
